@extends('layouts.clone.layoutwhite', ['local' => false]) 
@section('content')
@include('front.white.steps')
@include('front.white.video')
@include('front.white.featuredintro')
@include('front.white.upload')
@include('front.white.howtoenter')
@include('front.white.rules')
@include('front.white.prizes')
@include('front.white.faq')
@endsection